"""Users

Revision ID: c3d2c28b645d
Revises: 
Create Date: 2025-03-24 02:34:45.241978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d2c28b645d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )

    # Insert default admin user
    users_table = sa.table(
        'users',
        sa.column('id', sa.Integer()),
        sa.column('name', sa.String(length=255)),
        sa.column('email', sa.String(length=255)),
        sa.column('password', sa.String(length=255)),
        sa.column('is_admin', sa.Boolean())
    )

    op.bulk_insert(users_table, [
        {
            'id': 1,
            'name': 'Admin',
            'email': 'adm@example.com',
            'password': '$2b$12$9P7uGuun1qwfwsUONOmq5uUzDYLkrNDY32jSDLnZcDH8dntrc8Nqm',
            'is_admin': True
        }
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###